- name: Configure controller A inventory-defined controller port definitions
  na_santricity_nvme_interface:
    ssid: "{{ eseries_ssid }}"
    api_url: "{{ eseries_api_url }}"
    api_username: "{{ eseries_api_username }}"
    api_password: "{{ eseries_api_password }}"
    validate_certs: "{{ eseries_validate_certs | default(omit) }}"
    controller: A
    channel: "{{ item['channel'] }}"
    address: "{{ item['address'] | default(omit) }}"
  loop: "{{ lookup('list', eseries_controller_nvme_ib_port['controller_a']['channel']) }}"
  when: "eseries_controller_nvme_ib_port is defined and eseries_controller_nvme_ib_port['controller_a'] is defined and
         eseries_controller_nvme_ib_port['controller_a']['channel'] is defined"

- name: Configure controller B inventory-defined controller port definitions
  na_santricity_nvme_interface:
    ssid: "{{ eseries_ssid }}"
    api_url: "{{ eseries_api_url }}"
    api_username: "{{ eseries_api_username }}"
    api_password: "{{ eseries_api_password }}"
    validate_certs: "{{ eseries_validate_certs | default(omit) }}"
    controller: B
    channel: "{{ item.channel }}"
    address: "{{ item['address'] | default(omit) }}"
  loop: "{{ lookup('list', eseries_controller_nvme_ib_port['controller_b']['channel']) }}"
  when: "eseries_controller_nvme_ib_port is defined and eseries_controller_nvme_ib_port['controller_b'] is defined and
         eseries_controller_nvme_ib_port['controller_b']['channel'] is defined"
