namespace: "netapp_eseries"
name: "santricity"
version: "1.0.1"
readme: "README.md"
authors:
  - Nathan Swartz (@ndswartz)
  - Michael Price (@lmprice)
dependencies:
license:
  - "BSD-3-Clause"
repository: "https://www.github.com/netapp-eseries/santricity"
documentation: ""
tags:
  - netapp
  - eseries
  - santricity
homepage: "https://www.github.com/netapp-eseries/santricity"
issues: ""
