namespace: "netapp_eseries"
description: "Latest content available for NetApp E-Series Ansible automation."
name: "santricity"
version: "2.0.2"
readme: "README.md"
authors:
  - "Vu Tran (@VuTran007)"
  - "Christian Whiteside (@mcwhiteside)"
dependencies: {}
license:
  - "BSD-3-Clause"
repository: "https://www.github.com/netapp/santricity"
documentation: "https://github.com/netapp/santricity"
tags:
  - netapp
  - eseries
  - santricity
homepage: "https://www.github.com/netapp/santricity"
issues: "https://github.com/netapp/santricity/issues"
