namespace: "netapp_eseries"
description: "Latest content available for NetApp E-Series Ansible automation."
name: "santricity"
version: "2.0.1"
readme: "README.md"
authors:
  - "Nathan Swartz (@swartzn)"
  - "Vu Tran (@VuTran007)"
  - "Joe McCormick (@iamjoemccormick)"
dependencies: {}
license:
  - "BSD-3-Clause"
repository: "https://www.github.com/netapp-eseries/santricity"
documentation: "https://www.netapp.com/us/media/tr-4574.pdf"
tags:
  - netapp
  - eseries
  - santricity
homepage: "https://www.github.com/netapp-eseries/santricity"
issues: "https://github.com/netappeseries/santricity/issues"
