- name: Configure SANtricity Web Services Proxy's passwords
  import_tasks: proxy_security.yml
  delegate_to: localhost
  run_once: true

- name: Build information for Web Services
  import_tasks: build_info.yml
  delegate_to: localhost
  tags:
    - always

- name: Configure SANtricity WebServices Proxy
  import_tasks: proxy.yml
  delegate_to: localhost
  run_once: true
  tags:
    - always
