- name: Configure controllers iSCSI interface ports
  import_tasks: interface/iscsi.yml
  delegate_to: localhost
  tags:
    - iscsi
  when: eseries_initiator_protocol == "iscsi"

- name: Configure controllers InfiniBand iSER interface ports
  import_tasks: interface/ib_iser.yml
  delegate_to: localhost
  tags:
    - ib_iser
  when: eseries_initiator_protocol == "ib_iser"

- name: Configure controllers NVMe interface ports over InfiniBand
  import_tasks: interface/nvme_ib.yml
  delegate_to: localhost
  tags:
    - nvme_ib
  when: eseries_initiator_protocol == "nvme_ib"

- name: Configure controllers NVMe interface ports on RoCE
  import_tasks: interface/nvme_ib.yml
  delegate_to: localhost
  tags:
    - nvme_roce
  when: eseries_initiator_protocol == "nvme_roce"
