- name: Ensure directory structure exists
  file:
    path: "{{ playbook_dir }}/{{ item }}"
    state: directory
  loop:
    - host_vars
    - group_vars

- name: Ensure inventory file exists
  template:
    src: inventory.j2
    dest: "{{ playbook_dir }}/{{ eseries_inventory_file }}.yml"

- name: Ensure playbook file exists
  template:
    src: playbook.j2
    dest: "{{ playbook_dir }}/{{ eseries_playbook_file }}.yml"

- name: Ensure group inventory files exists
  copy:
    dest: "{{ playbook_dir }}/group_vars/{{ eseries_group_name }}.yml"
    content: "{{ eseries_group_defaults | to_nice_yaml }}"
  when: eseries_group_defaults is defined

- name: Ensure group inventory files exists
  copy:
    dest: "{{ playbook_dir }}/group_vars/{{ item }}.yml"
    content: "{{ eseries_groups[item] | to_nice_yaml }}"
  loop: "{{ lookup('list', (eseries_groups.keys() | list)) }}"
  when: eseries_groups is defined

- name: Ensure array inventory files exists
  copy:
    dest: "{{ playbook_dir }}/host_vars/{{ item }}.yml"
    content: "{{ eseries_arrays[item] | combine(eseries_arrays_common_templates | default()) | to_nice_yaml }}"
  loop: "{{ lookup('list', (eseries_arrays.keys() | list)) }}"
  when: eseries_arrays is defined
