- name: Ensure client-side certificates are installed
  nac_santricity_client_certificate:
    ssid: "{{ eseries_ssid }}"
    api_url: "{{ eseries_api_url }}"
    api_username: "{{ eseries_api_username }}"
    api_password: "{{ eseries_api_password }}"
    validate_certs: "{{ eseries_validate_certs | default(omit) }}"
    certificates: "{{ eseries_client_certificate_certificates }}"
  when: eseries_client_certificate_certificates is defined
  tags:
    - certificates
