- name: Ensure drive firmware is properly configured
  nac_santricity_drive_firmware:
    ssid: "{{ eseries_ssid }}"
    api_url: "{{ eseries_api_url }}"
    api_username: "{{ eseries_api_username }}"
    api_password: "{{ eseries_api_password }}"
    validate_certs: "{{ eseries_validate_certs | default(omit) }}"
    firmware: "{{ eseries_drive_firmware_firmware_list }}"
    wait_for_completion: "{{ eseries_drive_firmware_wait_for_completion | default(true) }}"
    ignore_inaccessible_drives: "{{ eseries_drive_firmware_ignore_inaccessible_drives | default(omit) }}"
    upgrade_drives_online: "{{ eseries_drive_firmware_upgrade_drives_online | default(omit) }}"
  when: eseries_drive_firmware_firmware_list is defined
  tags:
    - firmware
    - drive_firmware

- name: Ensure controller firmware is properly configured
  nac_santricity_firmware:
    ssid: "{{ eseries_ssid }}"
    api_url: "{{ eseries_api_url }}"
    api_username: "{{ eseries_api_username }}"
    api_password: "{{ eseries_api_password }}"
    validate_certs: "{{ eseries_validate_certs | default(omit) }}"
    nvsram: "{{ eseries_firmware_nvsram | default('') }}"
    firmware: "{{ eseries_firmware_firmware | default('') }}"
    wait_for_completion: "{{ eseries_firmware_wait_for_completion | default(true) }}"
    ignore_health_check: "{{ eseries_firmware_ignore_health_check | default(omit) }}"
  when: eseries_firmware_nvsram is defined or eseries_firmware_firmware is defined
  tags:
    - firmware
    - controller_firmware

