- name: Ensure ASUP configuration
  nac_santricity_asup:
    ssid: "{{ eseries_ssid }}"
    api_url: "{{ eseries_api_url }}"
    api_username: "{{ eseries_api_username }}"
    api_password: "{{ eseries_api_password }}"
    validate_certs: "{{ eseries_validate_certs | default(omit) }}"
    state: "{{ eseries_asup_state }}"
    active: "{{ eseries_asup_active | default(omit)}}"
    days: "{{ eseries_asup_days | default(omit) }}"
    start: "{{ eseries_asup_start | default(omit) }}"
    end: "{{ eseries_asup_end | default(omit) }}"
    method: "{{ eseries_asup_method | default(omit) }}"
    routing_type: "{{ eseries_asup_routing_type | default(omit) }}"
    proxy: "{{ eseries_asup_proxy | default(omit) }}"
    email: "{{ eseries_asup_email | default(omit) }}"
    validate: "{{ eseries_asup_validate | default(omit) }}"
  when: eseries_asup_state is defined
  tags:
    - logging
    - asup

- name: Ensure auditLog configuration
  nac_santricity_auditlog:
    ssid: "{{ eseries_ssid }}"
    api_url: "{{ eseries_api_url }}"
    api_username: "{{ eseries_api_username }}"
    api_password: "{{ eseries_api_password }}"
    validate_certs: "{{ eseries_validate_certs | default(omit) }}"
    force: "{{ eseries_auditlog_force | default(omit) }}"
    full_policy: "{{ eseries_auditlog_full_policy | default(omit) }}"
    log_level: "{{ eseries_auditlog_log_level | default(omit) }}"
    max_records: "{{ eseries_auditlog_max_records | default(omit) }}"
    threshold: "{{ eseries_auditlog_threshold | default(omit) }}"
  tags:
    - logging
    - auditlog

- name: Ensure syslog configuration
  nac_santricity_syslog:
    ssid: "{{ eseries_ssid }}"
    api_url: "{{ eseries_api_url }}"
    api_username: "{{ eseries_api_username }}"
    api_password: "{{ eseries_api_password }}"
    validate_certs: "{{ eseries_validate_certs | default(omit) }}"
    state: "{{ eseries_syslog_state }}"
    address: "{{ eseries_syslog_address }}"
    test: "{{ eseries_syslog_test | default(omit) }}"
    protocol: "{{ eseries_syslog_protocol | default(omit) }}"
    port: "{{ eseries_syslog_port | default(omit) }}"
    components: "{{ eseries_syslog_components | default(omit) }}"
  when: eseries_syslog_state is defined and eseries_syslog_address is defined
  tags:
    - logging
    - syslog

