- name: Configure SANtricity Web Services Proxy's passwords
  import_tasks: proxy_security.yml
  delegate_to: localhost
  run_once: true
  tags:
    - always

- name: Discover Web Services REST API url
  import_tasks: discovery.yml
  delegate_to: localhost
  tags:
    - always

- name: Configure SANtricity WebServices Proxy
  import_tasks: proxy.yml
  delegate_to: localhost
  run_once: true
  tags:
    - always

- name: Ensure security settings are configured
  import_tasks: security.yml
  delegate_to: localhost
  ignore_errors: true

- name: Ensure management interfaces are configured
  import_tasks: interface.yml
  delegate_to: localhost
  tags:
    - interface
    - ntp
    - dns
    - ssh

- name: Ensure all global system settings are configured
  import_tasks: system.yml
  delegate_to: localhost
  ignore_errors: true

- name: Ensure event logging has been configured
  import_tasks: logging.yml
  delegate_to: localhost
  ignore_errors: true

- name: Ensure drive and controller firmware are correct
  import_tasks: firmware.yml
  delegate_to: localhost
  ignore_errors: true
