- name: Set current storage system credentials
  include_role:
    name: netapp_eseries.santricity.nar_santricity_common
    tasks_from: build_info.yml
  when: current_eseries_api_url is not defined
  tags:
    - always

- name: Ensure security settings are configured
  import_tasks: security.yml

- name: Ensure management interfaces are configured
  include_tasks: interface.yml
  when: "eseries_management_interfaces['controller_a'] is defined or eseries_management_interfaces['controller_b'] is defined"
  tags:
    - interface
    - ntp
    - dns
    - ssh

- name: Ensure all global system settings are configured
  import_tasks: system.yml

- name: Ensure event logging has been configured
  import_tasks: logging.yml

- name: Ensure drive and controller firmware are correct
  import_tasks: firmware.yml
