- name: Ensure proxy admin password has been set
  na_santricity_auth:
    ssid: proxy
    api_url: "{{ item['key'] }}"
    api_username: "{{ item['value']['proxy_username'] }}"
    api_password: "{{ item['value']['current_password'] | default(item['value']['proxy_password']) }}"
    validate_certs: "{{ item['value']['proxy_validate_certs'] | default(omit) }}"
    user: admin
    password: "{{ item['value']['proxy_password'] }}"
  loop: "{{ lookup('dict', proxy_admin, wantlist=True) }}"
  vars:
    proxy_admin: |-
      {#- Build a dictionary of all inventoried proxies keyed by their api url #}
      {%- set systems = {} %}
      {%- for array in ansible_play_hosts_all %}
        {%- if "eseries_proxy_api_url" in hostvars[array] and
               "eseries_proxy_api_username" in hostvars[array] and hostvars[array]["eseries_proxy_api_username"] == "admin" and
               "eseries_proxy_api_password" in hostvars[array] %}
          {%- if systems.update({hostvars[array]["eseries_proxy_api_url"]: {
            "proxy_username": hostvars[array]["eseries_proxy_api_username"],
            "proxy_password": hostvars[array]["eseries_proxy_api_password"],
            "current_proxy_password": hostvars[array]["eseries_proxy_current_api_password"] | default(omit),
            "proxy_default_password": hostvars[array]["eseries_proxy_default_system_password"] | default(omit),
            "proxy_validate_certs": hostvars[array]["eseries_proxy_api_validate_certs"] | default(omit)}}) %}
          {%- endif %}
        {%- endif %}
      {%- endfor %}
      {{ systems }}

- name: Ensure proxy non-admin passwords have been set
  na_santricity_auth:
    ssid: proxy
    api_url: "{{ item['value']['proxy_url'] }}"
    api_username: "{{ item['value']['proxy_url_username'] }}"
    api_password: "{{ item['value']['proxy_url_password'] }}"
    validate_certs: "{{ eseries_proxy_api_validate_certs | default(omit) }}"
    user: "{{ item['value']['proxy_username'] }}"
    password: "{{ item['value']['proxy_password'] }}"
  loop: "{{ lookup('dict', proxy_non_admin, wantlist=True) }}"
  vars:
    proxy_non_admin: |-
      {#- Build a dictionary of all inventoried proxies keyed by their api url containing non-admin usernames/passwords #}
      {%- set systems = {} %}
      {%- for array in ansible_play_hosts_all %}
        {%- if "eseries_proxy_api_url" in hostvars[array] and
               "eseries_proxy_api_username" in hostvars[array] and
               "eseries_proxy_api_password" in hostvars[array] and
               "eseries_proxy_non_admin_authentication" in hostvars[array] and hostvars[array]["eseries_proxy_non_admin_authentication"] %}
          {%- for username in (hostvars[array]["eseries_proxy_non_admin_authentication"].keys() | list) %}
            {%- if systems.update({[hostvars[array]["eseries_proxy_api_url"], username] | join("-"): {
              "proxy_url": hostvars[array]["eseries_proxy_api_url"],
              "proxy_url_username": hostvars[array]["eseries_proxy_api_username"],
              "proxy_url_password": hostvars[array]["eseries_proxy_api_password"],
              "proxy_username": username,
              "proxy_password": hostvars[array]["eseries_proxy_non_admin_authentication"][username]}}) %}
            {%- endif %}
          {%- endfor %}
        {%- endif %}
      {%- endfor %}
      {{ systems }}
