- name: Ensure storage array has the correct array globals
  na_santricity_global:
    ssid: "{{ eseries_ssid }}"
    api_url: "{{ current_eseries_api_url }}"
    api_username: "{{ eseries_api_username }}"
    api_password: "{{ eseries_api_password }}"
    validate_certs: "{{ eseries_validate_certs | default(omit) }}"
    name: "{{ eseries_system_name | default(omit) }}"
    cache_block_size: "{{ eseries_system_cache_block_size | default(omit) }}"
    cache_flush_threshold: "{{ eseries_system_cache_flush_threshold | default(omit) }}"
    automatic_load_balancing: "{{ eseries_system_autoload_balance | default(omit) }}"
    host_connectivity_reporting: "{{ eseries_system_host_connectivity_reporting | default(omit) }}"
    default_host_type: "{{ eseries_system_default_host_type | default(omit)}}"
  when: eseries_system_name is defined
  tags:
    - system
