galaxy_info:
  author: NetApp
  description: Configures BeeGFS parallel file system with NetApp E-Series storage systems.
  company: NetApp
  license: BSD
  min_ansible_version: 2.5
  platforms:
    - name: EL
      versions:
      - all
    - name: Ubuntu
      versions:
      - all
  galaxy_tags:
    - eseries
    - beegfs
    - storage

dependencies: []