- name: Add BeeGFS apt respository
  apt_key:
    url: "{{ beegfs_repository_deb_gpgkey }}"
    state: present
  become: yes
- apt_repository:
    state: present
    repo: "deb [arch=amd64] {{ beegfs_repository_deb_base_url }} stretch non-free"
    update_cache: yes
  become: yes

- name: Ensure BeeGFS management package is installed
  apt:
    state: latest
    name:
      - beegfs-mgmtd
  become: yes
  when: '"management" in beegfs_node_roles'

- name: Ensure BeeGFS metadata package is installed
  apt:
    state: latest
    name:
      - beegfs-meta
  become: yes
  when: '"metadata" in beegfs_node_roles'

- name: Ensure BeeGFS storage package is installed
  apt:
    state: latest
    name:
      - beegfs-storage
  become: yes
  when: '"storage" in beegfs_node_roles'

- name: Ensure BeeGFS infiniband package is installed
  apt:
    state: latest
    name:
      - libbeegfs-ib
  when: '("storage" in beegfs_node_roles or "metadata" in beegfs_node_roles) and beegfs_enable_rdma'

- name: Ensure BeeGFS client package is installed
  apt:
    state: latest
    name:
      - beegfs-client
      - beegfs-helperd
      - beegfs-utils
      - libelf-dev
  when: '"client" in beegfs_node_roles'

- name: Ensure NTP is installed
  apt:
    state: latest
    name: ntp
  when: beegfs_ntp_enabled == True

- name: Ensure Chrony is uninstalled
  apt:
    state: absent
    name: chrony
  when: beegfs_ntp_enabled == True
