- name: Add BeeGFS YUM repository
  yum_repository:
    name: beegfs
    description: BeeGFS YUM Repo
    file: beegfs_rhel7
    baseurl: "{{ beegfs_repository_base_url }}"
    enabled: yes
    gpgcheck: yes
    gpgkey: "{{ beegfs_repository_gpgkey }}"

- name: Get kernal version
  shell: "uname -r"
  register: shell_output
  failed_when: "shell_output.rc != 0"
  changed_when: False

- name: Ensure kernel-devel is installed
  yum:
    name: "kernel-devel-{{ shell_output.stdout_lines[0] }}"

- name: Ensure BeeGFS management package is installed
  yum:
    state: latest
    name: beegfs-mgmtd
  when: '"management" in beegfs_node_roles'

- name: Ensure BeeGFS metadata package is installed
  yum:
    state: latest
    name:
      - beegfs-meta
      - device-mapper-multipath
  when: '"metadata" in beegfs_node_roles'

- name: Ensure BeeGFS storage package is installed
  yum:
    state: latest
    name:
      - beegfs-storage
      - device-mapper-multipath
  when: '"storage" in beegfs_node_roles'

- name: Ensure BeeGFS infiniband package is installed
  yum:
    state: latest
    name: libbeegfs-ib
  when: '("storage" in beegfs_node_roles or "metadata" in beegfs_node_roles) and beegfs_enable_rdma'

- name: Ensure BeeGFS client package is installed
  yum:
    state: latest
    name:
      - beegfs-client
      - beegfs-helperd
      - beegfs-utils
  when: '"client" in beegfs_node_roles'

- name: Ensure NTP is installed
  yum:
    state: latest
    name: ntp
  when: beegfs_ntp_enabled == True

- name: Ensure Chrony is uninstalled
  yum:
    state: absent
    name: chrony
  when: beegfs_ntp_enabled == True
