- name: Gather facts about E-Series storage systems
  setup:
  delegate_to: localhost
  delegate_facts: true
  loop: "{{ lookup('list', groups[ansible_play_hosts_all] | default(ansible_play_hosts_all)) }}"

- name: Retrieve initiator volume list from E-Series storage systems
  na_santricity_facts:
    ssid: "{{ hostvars[item]['eseries_ssid'] }}"
    api_url: "{{ hostvars[item]['eseries_api_url'] }}"
    api_username: "{{ hostvars[item]['eseries_api_username'] }}"
    api_password: "{{ hostvars[item]['eseries_api_password'] }}"
    validate_certs: "{{ hostvars[item]['eseries_validate_certs'] }}"
  loop: "{{ lookup('list', groups[ansible_play_hosts_all] | default(ansible_play_hosts_all)) }}"
  register: storage_array_facts

- name: Populate eseries_volumes specific
  set_fact:
    eseries_volumes: |
      {%- set volumes = [] %}
      {%- for result in storage_array_facts["results"] %}
        {%- if "storage_array_facts" in (result.keys() | list) and
               "netapp_volumes_by_initiators" in (result["storage_array_facts"].keys() | list) %}
          {%- if inventory_hostname in (result["storage_array_facts"]["netapp_volumes_by_initiators"].keys() | list) %}
            {%- if volumes.extend(result["storage_array_facts"]["netapp_volumes_by_initiators"][inventory_hostname]) %}{%- endif %}
          {%- endif %}
        {%- endif %}
      {%- endfor %}
      {{ volumes }}

- name: Determine all volumes tagged for BeeGFS storage volumes
  set_fact:
    storage_volumes: |
      {%- set volumes = [] %}
      {%- for volume in eseries_volumes %}
        {%- if volume["workload_name"] == "beegfs_storage" %}
          {%- if volumes.append(volume) %}{%- endif %}
        {%- endif %}
      {%- endfor %}
      {{ volumes }}

- name: Determine all volumes tagged for BeeGFS metadata volumes
  set_fact:
    metadata_volumes: |
      {%- set volumes = [] %}
      {%- for volume in eseries_volumes %}
        {%- if volume["workload_name"] == "beegfs_metadata" %}
          {%- if volumes.append(volume) %}{%- endif %}
        {%- endif %}
      {%- endfor %}
      {{ volumes }}
