- name: Collect NetApp E-Series volume information
  import_tasks: collect_volume_facts.yml
  when: '"storage" in beegfs_node_roles or "metadata" in beegfs_node_roles'
  tags:
    - beegfs
    - beegfs_storage
    - beegfs_metadata

- name: Install BeeGFS packages
  block:
  - import_tasks: packages/debian_packages.yml
    when: ansible_facts['os_family'] | lower == 'debian'
    become: True
  - import_tasks: packages/redhat_packages.yml
    when: ansible_facts['os_family'] | lower == 'redhat'
    become: True
  tags:
    - beegfs
    - beegfs_packages
    - beegfs_management
    - beegfs_storage
    - beegfs_metadata
    - beegfs_client
    - beegfs_ntp

- name: Mount BeeGFS storage and metadata volumes
  import_tasks: mount.yml
  become: yes
  when: '"storage" in beegfs_node_roles or "metadata" in beegfs_node_roles'
  tags:
    - beegfs
    - beegfs_volumes
    - beegfs_storage
    - beegfs_metadata

- name: Ensure NTP is properly configured
  import_tasks: configure/common.yml
  become: yes
  when: beegfs_ntp_enabled == True
  tags:
    - beegfs
    - beegfs_ntp
    - beegfs_management
    - beegfs_storage
    - beegfs_metadata
    - beegfs_client

- name: Open firewall ports for BeeGFS
  import_tasks: firewall.yml
  become: yes
  when: beegfs_open_firewall_ports == True
  tags:
    - beegfs
    - beegfs_firewall_ports
    - beegfs_management
    - beegfs_storage
    - beegfs_metadata
    - beegfs_client

- name: Configure BeeGFS management service
  import_tasks: configure/management.yml
  become: True
  when: '"management" in beegfs_node_roles'
  tags:
    - beegfs
    - beegfs_management

- name: Configure BeeGFS storage service
  import_tasks: configure/storage.yml
  become: True
  when: '"storage" in beegfs_node_roles'
  tags:
    - beegfs
    - beegfs_volumes
    - beegfs_storage

- name: Configure BeeGFS metadata service
  import_tasks: configure/metadata.yml
  become: True
  when: '"metadata" in beegfs_node_roles'
  tags:
    - beegfs
    - beegfs_volumes
    - beegfs_metadata

- name: Configure BeeGFS client service
  import_tasks: configure/client.yml
  become: True
  when: '"client" in beegfs_node_roles'
  tags:
    - beegfs
    - beegfs_client
